& "$PSScriptRoot\..\gitmodules\mod-installer\build_all.ps1" `
  -Version "2.0.0" `
  -PreReleaseVersion "beta.1" `
  -OutputFilePrefix "Metastasis_Full_Patched" `
  -ModName "MINERVA: Metastasis" `
  -ModFolder "metastasis" `
  -ModFilesPath "$PSScriptRoot\..\game" `
  -ModBaseFilesUrl "https://github.com/HL2-Mods-Legacy-Project/hl2-legacy-registry/releases/download/metastasis3/Metastasis-3-Full-Patched-Original.zip" `
  -ModBaseFilesUrlHash "74d1706721ee29c3a1a38138a71b4aef2a728ce8ea7bef5d5b932075103772ec" `
  -ModReadmePath "README.txt" `
  -PublishPath "$PSScriptRoot\..\artifacts\publish"
